### ISSUE TITLE
xclip is not installed by default. 

### ISSUE THREAD

**Issue by ststeiger** [SimonCropp/TextCopy#131]
xclip is not installed by default. 
So your clipboard library does not work on Linux. 

However, if you use KDE, klipper registers with dbus, and you can just use the DBus-protocol to get and set clipboard text. 

Gnome does not provide any API except lots of XOrg calls.

**Comment by SimonCropp** [comment]
@ststeiger happy to accept a PR that add support for this

**Comment by SimonCropp** [comment]
let me know if you ever get around to doing a PR

**Comment by ststeiger** [comment]
Klipper DBus-Interface: https://pastebin.com/HDsRs5aG
Actual Clipboard Code: https://pastebin.com/xSHPzPEq
Abstract class: https://pastebin.com/939kDvP8

Requires [Tmds.Dbus](https://github.com/tmds/Tmds.DBus) for Dbus, 
and [AsyncEx](https://github.com/StephenCleary/AsyncEx) for synchronizing async in the abstract class (using async in get/set property).

**Comment by SimonCropp** [comment]
@ststeiger i appreciate the pointers. although i dont have time to reverse engineer all that context, and since this currently works for all my scenarios, i am unlikely get to it in the furture.
