### ISSUE TITLE
Linux - Clipboard.SetText does not update the expected clipboard buffer

### ISSUE THREAD

**Issue by duncanawoods** [SimonCropp/TextCopy#15]
I am using Ubuntu 18.04 with the latest version `xclip 0.12+svn84-4build1`. 

## Problem

Calling `Clipboard.SetText` does not update the clipboard that can be pasted with ctrl-v.

## Cause

This is because `LinuxClipboard.SetText` is using `xclip` to write to the `PRIMARY` buffer which means it can be pasted into terminals with a middle-click but not the `CLIPBOARD` which allows for the expected windows\osx style copy/paste behaviour between applications. 

The three possible buffers `xclip` can write to are described here:

https://specifications.freedesktop.org/clipboards-spec/clipboards-latest.txt

Which says:

* `PRIMARY` is an "easter egg" for expert users, regular users can just ignore it; it's normally pastable only via middle-mouse-click.
* `SECONDARY` No one ever does anything interesting with SECONDARY as far as I can
tell.
* `CLIPBOARD` for the Windows-style cut/copy/paste menu items

## Fix

To fix this, explicitly choose the clipboard as the destination buffer by changing `LinuxClipboard.cs`:

e.g.

``` csharp
BashRunner.Run($"cat {tempFileName} | xclip");
```

to:

``` csharp
BashRunner.Run($"cat {tempFileName} | xclip -selection clipboard");
```

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.
