### ISSUE TITLE
.NET Standard issues on .NET Framework 4.7.1

### ISSUE THREAD

**Issue by stevenengland** [SimonCropp/TextCopy#37]
As this is not a bug of this lib but of .NET itself, I chose to create a feature request instead of a bug report. The library uses something from System.Runtime.InteropServices.RuntimeInformation which in a certain scenario fails, see the Issue connected with this.
#### Is the feature request related to a problem

related to: [ISSUE](https://github.com/dotnet/standard/issues/567)

#### Describe the solution

"adding a net461 asset is going to be the fastest way for you to unblock your customers. If you also have a netstandard 2.0 asset then you will ensure that the code remains compatible with .NET Standard and that it can run on 4.6.1"

See comment: [COMMENT](https://github.com/dotnet/standard/issues/567#issuecomment-341615176)

#### Describe alternatives considered

-

#### Additional context

-

**Comment by SimonCropp** [comment]
i am tempted to take the least effort approach here and say "only net472 are supported"

**Comment by stevenengland** [comment]
Hi Simon, absolutely comprehensible. A few people like me will need to reconsider or rewrite the lib then because we cannot upgrade. But I think this is bearable :)

**Comment by SimonCropp** [comment]
Ok i pushed a 471 of moving to 472

**Comment by SimonCropp** [comment]
Whats your eta of moving to net 472?

**Comment by stevenengland** [comment]
Hi Simon, what do you mean by that (eta 472)? Sorry :)

**Comment by SimonCropp** [comment]
i was curious when you plan on moving to net 472

**Comment by stevenengland** [comment]
> i was curious when you plan on moving to net 472

Ah ok. Well, that is not up to me, it is third party infrastructure and I am the smallest cog in this big wheel :)
