### ISSUE TITLE
Compiler warning and runtime exception on UWP Release

### ISSUE THREAD

**Issue by HaikuJock** [SimonCropp/TextCopy#79]
The library works fine on Debug UWP builds but gives the compiler warnings for each of the unsupported windows p/invoke calls when built in Release. For example:
```
MCG : warning MCG0007: Unresolved P/Invoke method 'user32.dll!CloseClipboard' for method 'System.Boolean WindowsClipboard.CloseClipboard()'.
 Calling this method would throw exception at runtime.
 Please make sure the P/Invoke either points to a Windows API allowed in UWP applications, or a native DLL that is part of the package. 
If for some reason your P/Invoke does not satisfy those requirements, please use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP APIs		
```
At runtime the promised exception is thrown when trying to cut, copy or paste.

This is using a UWP with a minimum target version of 10.0.16299. I don't see the clipboard windows calls listed in the available APIs:
https://docs.microsoft.com/en-us/uwp/win32-and-com/win32-and-com-for-uwp-apps

I will attempt a fix for my own app that uses the UWP Clipboard https://docs.microsoft.com/en-us/windows/uwp/app-to-app/copy-and-paste

If that works I'll make a PR for this library.

**Comment by HaikuJock** [comment]
Two problems with the UWP Clipboard:
- It can only be accessed from the main thread
- It's GetText method is asynchronous

This is what I've implemented for my own app:
```
using System;
using System.Threading.Tasks;
using Windows.ApplicationModel.Core;
using Windows.ApplicationModel.DataTransfer;
using Windows.UI.Core;

namespace A.Namespace
{
    public interface TextClipboarding
    {
        void SetText(string text);
        string GetText();
    }

    class UwpTextClipboard : TextClipboarding
    {
        string clipboardText = "";

        internal UwpTextClipboard()
        {
#pragma warning disable CS4014 // Because this call is not awaited, execution of the current method continues before the call is completed
            GetTextFromClipboard();
#pragma warning restore CS4014 // Because this call is not awaited, execution of the current method continues before the call is completed
            Clipboard.ContentChanged += async (s, e) => await GetTextFromClipboard();
        }

        public string GetText()
        {
            return clipboardText;
        }

        public void SetText(string text)
        {
            DataPackage dataPackage = new DataPackage();
            dataPackage.SetText(text);
#pragma warning disable CS4014 // Because this call is not awaited, execution of the current method continues before the call is completed
            CoreApplication.MainView.CoreWindow.Dispatcher.RunAsync(CoreDispatcherPriority.Normal, () => Clipboard.SetContent(dataPackage));
#pragma warning restore CS4014 // Because this call is not awaited, execution of the current method continues before the call is completed
        }

        async Task GetTextFromClipboard()
        {
            DataPackageView initialDataPackageView = Clipboard.GetContent();

            if (initialDataPackageView.Contains(StandardDataFormats.Text))
            {
                clipboardText = await initialDataPackageView.GetTextAsync();
            }
        }
    }
}
```
The `UwpTextClipboard ` must be constructed on the main thread but can then be used from other threads. Pretty horrible.

I don't see how to distinguish UWP in the context of this library so I'm not sure how to proceed with a PR.

**Comment by SimonCropp** [comment]
can u try 2.0-beta.1

note that the methods are now async

**Comment by HaikuJock** [comment]
I don't see that version on NuGet. I can try building from source.

**Comment by SimonCropp** [comment]
try again. i had some trouble pushing

**Comment by SimonCropp** [comment]
showing up now https://www.nuget.org/packages/TextCopy/2.0.0-beta.1

**Comment by HaikuJock** [comment]
OK. Got it now. Just need to figure out how to await the call to GetText.

**Comment by HaikuJock** [comment]
`SetText` works fine.

`GetText` is working OK provided it's called from the UI thread. I'm calling it from a worker thread so I have to run it with `CoreApplication.MainView.CoreWindow.Dispatcher.RunAsync` and then `Thread.Sleep(100)`. Calling it from a worker thread without this throws an exception with the message `Activating a single-threaded class from MTA is not supported`

Given that the UI thread requirement is UWP specific anyway I intend to use my own wrapper for UWP and TextCopy 1.7.1 for my Mac and non-UWP Windows application.

It might be worth waiting to see if there is more demand for this before releasing 2.0, my usage may be unique.

**Comment by SimonCropp** [comment]
can u try beta 2 without your CoreApplication.MainView.CoreWindow.Dispatcher change on gettext

**Comment by HaikuJock** [comment]
Tried that but the call doesn't return from `await GetText`
I see `Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.dll` in the Output window.
Looking at your changes the only difference I see with my own use of `RunAsync` with beta 1 was that I added an `AsTask()` call after `RunAsync`. That changes it from an `IAsyncAction` to a `Task`. I don't understand why that would make a difference though.

**Comment by SimonCropp** [comment]
ok the problem was the `UapClipboard.GetContent();` aslo had to be inside the `Dispatcher.RunAsync`

can u try beta 3

**Comment by HaikuJock** [comment]
I'm getting null back from my call to `await Clipboard.GetText()` but might be doing something wrong. I'll have another try this evening.

**Comment by HaikuJock** [comment]
I think there's definitely something weird with my setup which I'm going to look into further.

I tried copying your test code by getting and setting on a thread and it worked fine.

I then tried repeatedly firing the get and set on new threads:

```
        public MainPage()
        {
            InitializeComponent();
            var thread1 = new Thread(TestClipboard);
            thread1.Start();
        }

        void TestClipboard()
        {
            var random = new Random();
            while (true)
            {
                var thread = new Thread(OutputClipboardText);
                thread.Start();
                Thread.Sleep(random.Next(1, 100) * 10);
            }
        }

        async void OutputClipboardText()
        {
            await TextCopy.Clipboard.SetText("AAA");
            var text = await TextCopy.Clipboard.GetText();
            Debug.WriteLine("Clipboard");
            if (text == null)
            {
                Debug.WriteLine("NULL");
            }
            else
            {
                Debug.WriteLine(text);
            }
        }
```
I found two things from this:
1. Sometimes the result of `GetText` was null
2. An unhandled exception was occasionally thrown with error code `CLIPBRD_E_CANT_OPEN`. I vaguely seeing code where you handled this for the .NET framework version. https://stackoverflow.com/questions/68666/clipbrd-e-cant-open-error-when-setting-the-clipboard-from-net

**Comment by SimonCropp** [comment]
can u submit a failing PR with that code?
